"""Standard educational portfolios used as QuantInvest benchmarks.

Generated from the user-provided QuantInvest standard portfolio specification.
These models are educational benchmarks, not personalized financial advice.
"""

from __future__ import annotations

STANDARD_PORTFOLIOS = [{'id': 'difensivo-globale-25-75',
  'name': 'Difensivo Globale 25/75',
  'originalName': 'Difensivo 1',
  'plan': 'plus',
  'category': 'defensive',
  'riskLevel': 2,
  'investorProfile': 'low',
  'suggestedHorizon': '3-5 anni',
  'description': 'Portafoglio difensivo globale pensato per investitori con bassa propensione al rischio. '
                 'Combina una quota azionaria contenuta con una forte componente obbligazionaria e strumenti '
                 'a duration molto breve in euro.',
  'warning': 'Può comunque subire oscillazioni in caso di rialzo dei tassi, crisi obbligazionarie o '
             'movimenti valutari sulla parte globale.',
  'holdings': [{'name': 'iShares MSCI ACWI',
                'isin': 'IE00B6R52259',
                'weight': 25.0,
                'role': 'Componente azionaria globale diversificata'},
               {'name': 'iShares Core Global Aggregate Bond',
                'isin': 'IE00BZ043R46',
                'weight': 40.0,
                'role': 'Componente obbligazionaria globale'},
               {'name': 'iShares EUR Ultrashort Bond',
                'isin': 'IE00BCRY6557',
                'weight': 35.0,
                'role': 'Stabilità, liquidità e bassa duration in euro'}]},
 {'id': 'difensivo-stabilita-oro',
  'name': 'Difensivo Stabilità & Oro',
  'originalName': 'Difensivo 2',
  'plan': 'plus',
  'category': 'defensive',
  'riskLevel': 2,
  'investorProfile': 'low',
  'suggestedHorizon': '3-5 anni',
  'description': 'Portafoglio difensivo con esposizione azionaria contenuta, componente obbligazionaria '
                 'corporate in euro e una piccola quota in oro come diversificatore.',
  'warning': 'L’oro può essere volatile e la componente corporate bond può soffrire in fasi di stress del '
             'credito.',
  'holdings': [{'name': 'iShares Core MSCI World',
                'isin': 'IE00B4L5Y983',
                'weight': 25.0,
                'role': 'Azionario globale sviluppato'},
               {'name': 'iShares Core EUR Corporate Bond',
                'isin': 'IE00B3F81R35',
                'weight': 45.0,
                'role': 'Obbligazioni corporate investment grade in euro'},
               {'name': 'iShares EUR Ultrashort Bond',
                'isin': 'IE00BCRY6557',
                'weight': 20.0,
                'role': 'Stabilità e riduzione della duration'},
               {'name': 'iShares Physical Gold',
                'isin': 'IE00B4ND3602',
                'weight': 10.0,
                'role': 'Diversificazione e protezione da scenari di stress'}]},
 {'id': 'ultra-difensivo-obbligazionario',
  'name': 'Ultra Difensivo Obbligazionario',
  'originalName': 'Difensivo 3',
  'plan': 'plus',
  'category': 'defensive',
  'riskLevel': 1,
  'investorProfile': 'low',
  'suggestedHorizon': '1-4 anni',
  'description': 'Portafoglio quasi interamente obbligazionario, pensato per investitori molto prudenti o '
                 'con bassa tolleranza alla volatilità.',
  'warning': 'Nonostante l’assenza di azionario, il portafoglio può comunque subire perdite in caso di '
             'rialzo dei tassi o peggioramento del mercato obbligazionario corporate.',
  'holdings': [{'name': 'iShares Core Global Aggregate Bond',
                'isin': 'IE00BZ043R46',
                'weight': 40.0,
                'role': 'Obbligazionario globale diversificato'},
               {'name': 'iShares EUR Ultrashort Bond',
                'isin': 'IE00BCRY6557',
                'weight': 30.0,
                'role': 'Stabilità e bassa duration'},
               {'name': 'iShares Core EUR Corporate Bond',
                'isin': 'IE00B3F81R35',
                'weight': 30.0,
                'role': 'Obbligazioni corporate investment grade in euro'}]},
 {'id': 'prudente-globale-distribuzione',
  'name': 'Prudente Globale Distribuzione',
  'originalName': 'Distribuzione 1',
  'plan': 'plus',
  'category': 'defensive',
  'riskLevel': 2,
  'investorProfile': 'low',
  'suggestedHorizon': '3-6 anni',
  'description': 'Portafoglio prudente e semplice, con azionario globale e forte componente obbligazionaria '
                 'europea.',
  'warning': 'La componente obbligazionaria può risentire del rialzo dei tassi. La quota azionaria può '
             'generare drawdown nelle fasi di crisi di mercato.',
  'holdings': [{'name': 'Vanguard FTSE All-World',
                'isin': 'IE00B3RBWM25',
                'weight': 30.0,
                'role': 'Azionario globale diversificato'},
               {'name': 'iShares Core EUR Corporate Bond',
                'isin': 'IE00B3F81R35',
                'weight': 35.0,
                'role': 'Obbligazioni corporate investment grade in euro'},
               {'name': 'iShares Core Euro Government Bond',
                'isin': 'IE00B4WXJJ64',
                'weight': 35.0,
                'role': 'Obbligazioni governative area euro'}]},
 {'id': 'dividend-prudente-usa',
  'name': 'Dividend Prudente USA',
  'originalName': 'Distribuzione 2',
  'plan': 'plus',
  'category': 'defensive',
  'riskLevel': 2,
  'investorProfile': 'low',
  'suggestedHorizon': '3-6 anni',
  'description': 'Portafoglio prudente orientato ai dividendi, con esposizione ad aziende USA dividend '
                 'aristocrats e una forte componente obbligazionaria in euro.',
  'warning': 'È più concentrato sugli Stati Uniti e sui titoli a dividendo rispetto a un portafoglio globale '
             'tradizionale.',
  'holdings': [{'name': 'SPDR S&P U.S. Dividend Aristocrats',
                'isin': 'IE00B6YX5D40',
                'weight': 30.0,
                'role': 'Azionario USA orientato ai dividendi'},
               {'name': 'iShares EUR Ultrashort Bond',
                'isin': 'IE00BCRY6557',
                'weight': 35.0,
                'role': 'Stabilità e liquidità in euro'},
               {'name': 'iShares Core EUR Corporate Bond',
                'isin': 'IE00B3F81R35',
                'weight': 35.0,
                'role': 'Obbligazioni corporate investment grade in euro'}]},
 {'id': 'moderato-globale-usa-tilt',
  'name': 'Moderato Globale USA Tilt',
  'originalName': 'Moderato 1',
  'plan': 'plus',
  'category': 'moderate',
  'riskLevel': 3,
  'investorProfile': 'moderate',
  'suggestedHorizon': '5-8 anni',
  'description': 'Portafoglio moderato con esposizione globale e sovrappeso controllato sugli Stati Uniti, '
                 'bilanciato da obbligazioni governative europee.',
  'warning': 'L’ACWI contiene già una quota rilevante di Stati Uniti: l’aggiunta dell’S&P 500 aumenta il '
             'peso del mercato USA. La componente bond 7-10 anni può soffrire in caso di rialzo dei tassi.',
  'holdings': [{'name': 'iShares MSCI ACWI',
                'isin': 'IE00B6R52259',
                'weight': 50.0,
                'role': 'Azionario globale diversificato'},
               {'name': 'iShares Core S&P 500',
                'isin': 'IE00B5BMR087',
                'weight': 15.0,
                'role': 'Sovrappeso sugli Stati Uniti'},
               {'name': 'Amundi Euro Government Bond 7-10Y',
                'isin': 'LU1287023185',
                'weight': 35.0,
                'role': 'Obbligazioni governative euro a duration intermedia'}]},
 {'id': 'moderato-world-cash-gold',
  'name': 'Moderato World Cash & Gold',
  'originalName': 'Moderato 2',
  'plan': 'plus',
  'category': 'moderate',
  'riskLevel': 3,
  'investorProfile': 'moderate',
  'suggestedHorizon': '5-8 anni',
  'description': 'Portafoglio moderato semplice, con azionario globale sviluppato, Treasury USA a breve '
                 'scadenza e oro.',
  'warning': 'La componente Treasury è in dollari USA, quindi può introdurre rischio cambio EUR/USD per un '
             'investitore europeo.',
  'holdings': [{'name': 'iShares Core MSCI World',
                'isin': 'IE00B4L5Y983',
                'weight': 60.0,
                'role': 'Azionario globale sviluppato'},
               {'name': 'iShares USD Treasury Bond 0-1yr',
                'isin': 'IE00BGSF1X88',
                'weight': 30.0,
                'role': 'Obbligazioni governative USA a brevissima scadenza'},
               {'name': 'iShares Physical Gold',
                'isin': 'IE00B4ND3602',
                'weight': 10.0,
                'role': 'Diversificazione e protezione da scenari di stress'}]},
 {'id': 'moderato-barbell-globale',
  'name': 'Moderato Barbell Globale',
  'originalName': 'Moderato 3',
  'plan': 'plus',
  'category': 'moderate',
  'riskLevel': 3,
  'investorProfile': 'moderate',
  'suggestedHorizon': '5-10 anni',
  'description': 'Portafoglio moderato avanzato con struttura barbell: azionario globale, small cap, bond '
                 'governativi lunghi, bond governativi brevi e oro.',
  'warning': 'La componente governativa 15-30 anni può oscillare molto in caso di rialzo dei tassi.',
  'holdings': [{'name': 'iShares Core MSCI World UCITS ETF Acc',
                'isin': 'IE00B4L5Y983',
                'weight': 50.0,
                'role': 'Azionario globale sviluppato'},
               {'name': 'SPDR MSCI World Small Cap UCITS ETF Acc',
                'isin': 'IE00BCBJG560',
                'weight': 10.0,
                'role': 'Esposizione a small cap globali'},
               {'name': 'iShares € Govt Bond 15-30yr UCITS ETF Dist',
                'isin': 'IE00B1FZS913',
                'weight': 15.0,
                'role': 'Obbligazioni governative euro a lunga duration'},
               {'name': 'iShares € Govt Bond 1-3yr UCITS ETF Acc',
                'isin': 'IE00B3VTMJ91',
                'weight': 15.0,
                'role': 'Obbligazioni governative euro a breve duration'},
               {'name': 'iShares Physical Gold ETC',
                'isin': 'IE00B4ND3602',
                'weight': 10.0,
                'role': 'Diversificazione e protezione da scenari di stress'}]},
 {'id': 'azionario-globale-aggressivo',
  'name': 'Azionario Globale Aggressivo',
  'originalName': 'Aggressivo 1',
  'plan': 'plus',
  'category': 'aggressive',
  'riskLevel': 5,
  'investorProfile': 'high',
  'suggestedHorizon': '10+ anni',
  'description': 'Portafoglio azionario globale aggressivo, costruito separando Stati Uniti, mercati '
                 'sviluppati ex-USA ed emergenti.',
  'warning': 'Portafoglio 100% azionario, quindi può subire drawdown elevati nelle fasi di crisi di mercato.',
  'holdings': [{'name': 'iShares Core S&P 500',
                'isin': 'IE00B5BMR087',
                'weight': 50.0,
                'role': 'Azionario USA large cap'},
               {'name': 'iShares MSCI World ex-USA',
                'isin': 'IE000R4ZNTN3',
                'weight': 30.0,
                'role': 'Azionario paesi sviluppati esclusi Stati Uniti'},
               {'name': 'iShares Core MSCI Emerging Markets',
                'isin': 'IE00BKM4GZ66',
                'weight': 20.0,
                'role': 'Azionario mercati emergenti'}]},
 {'id': 'tech-growth-em-ex-china',
  'name': 'Tech Growth & EM ex-China',
  'originalName': 'Aggressivo 2',
  'plan': 'plus',
  'category': 'aggressive',
  'riskLevel': 5,
  'investorProfile': 'high',
  'suggestedHorizon': '10+ anni',
  'description': 'Portafoglio aggressivo orientato a tecnologia, Nasdaq 100 e mercati emergenti esclusa '
                 'Cina, con una piccola componente obbligazionaria a tasso variabile.',
  'warning': 'Molto concentrato su growth/tech USA ed emergenti. Può essere molto volatile.',
  'holdings': [{'name': 'iShares Nasdaq 100',
                'isin': 'IE00B53SZB19',
                'weight': 60.0,
                'role': 'Azionario growth e tecnologia USA'},
               {'name': 'iShares MSCI EM ex-China',
                'isin': 'IE00BMG6Z448',
                'weight': 25.0,
                'role': 'Mercati emergenti esclusa Cina'},
               {'name': 'iShares USD Floating Rate Bond',
                'isin': 'IE00BDFGJ627',
                'weight': 15.0,
                'role': 'Componente obbligazionaria floating rate in USD'}]},
 {'id': 'aggressivo-multi-asset-growth',
  'name': 'Aggressivo Multi-Asset Growth',
  'originalName': 'Aggressivo 3',
  'plan': 'plus',
  'category': 'aggressive',
  'riskLevel': 5,
  'investorProfile': 'high',
  'suggestedHorizon': '10+ anni',
  'description': 'Portafoglio aggressivo multi-asset con azionario globale equal weight, tilt Nasdaq, '
                 'commodity e Treasury USA a lunga scadenza.',
  'warning': 'Treasury lunghi e commodity possono essere molto volatili. Non è un portafoglio difensivo.',
  'holdings': [{'name': 'Invesco MSCI World Equal Weight',
                'isin': 'IE000OEF25S1',
                'weight': 65.0,
                'role': 'Azionario globale equal weight'},
               {'name': 'iShares Nasdaq 100',
                'isin': 'IE00B53SZB19',
                'weight': 20.0,
                'role': 'Sovrappeso growth/tecnologia USA'},
               {'name': 'Invesco Bloomberg Commodity',
                'isin': 'IE00BD6FTQ80',
                'weight': 7.5,
                'role': 'Diversificazione tramite commodity'},
               {'name': 'iShares USD Treasury Bond 20+yr',
                'isin': 'IE00BFM6TC58',
                'weight': 7.5,
                'role': 'Obbligazioni governative USA a lunga scadenza'}]},
 {'id': 'growth-value-globale',
  'name': 'Growth & Value Globale',
  'originalName': 'Aggressivo 4',
  'plan': 'plus',
  'category': 'aggressive',
  'riskLevel': 5,
  'investorProfile': 'high',
  'suggestedHorizon': '10+ anni',
  'description': 'Portafoglio azionario globale aggressivo con emergenti, tilt value e oro come '
                 'diversificatore.',
  'warning': 'Forte esposizione azionaria globale. Il tilt value può sottoperformare per lunghi periodi '
             'rispetto al mercato globale.',
  'holdings': [{'name': 'iShares Core MSCI World',
                'isin': 'IE00B4L5Y983',
                'weight': 60.0,
                'role': 'Azionario globale sviluppato'},
               {'name': 'iShares Core MSCI Emerging Markets',
                'isin': 'IE00BKM4GZ66',
                'weight': 15.0,
                'role': 'Azionario mercati emergenti'},
               {'name': 'Xtrackers MSCI World Value',
                'isin': 'IE00BL25JM42',
                'weight': 15.0,
                'role': 'Tilt fattoriale value globale'},
               {'name': 'iShares Physical Gold',
                'isin': 'IE00B4ND3602',
                'weight': 10.0,
                'role': 'Diversificazione e protezione da scenari di stress'}]},
 {'id': 'income-bond-dinamico',
  'name': 'Income Bond Dinamico',
  'originalName': 'Income 1',
  'plan': 'advanced',
  'category': 'income',
  'riskLevel': 3,
  'investorProfile': 'moderate',
  'suggestedHorizon': '5-8 anni',
  'description': 'Portafoglio income obbligazionario dinamico, con governativi globali, corporate investment '
                 'grade, una quota high yield e Treasury USA lunghi.',
  'warning': 'Income non significa assenza di rischio. La componente high yield ha rischio credito e i '
             'Treasury lunghi hanno rischio duration.',
  'holdings': [{'name': 'iShares EUR High Yield Corporate Bond',
                'isin': 'IE00B66F4759',
                'weight': 20.0,
                'role': 'Obbligazioni corporate high yield in euro'},
               {'name': 'iShares Global Government Bond',
                'isin': 'IE00BKT6FT27',
                'weight': 50.0,
                'role': 'Obbligazioni governative globali'},
               {'name': 'iShares Core EUR Corporate Bond',
                'isin': 'IE00B3F81R35',
                'weight': 20.0,
                'role': 'Obbligazioni corporate investment grade in euro'},
               {'name': 'iShares USD Treasury Bond 20+yr',
                'isin': 'IE00BD8PGZ49',
                'weight': 10.0,
                'role': 'Treasury USA a lunga scadenza'}]},
 {'id': 'income-europa-dividendi',
  'name': 'Income Europa & Dividendi',
  'originalName': 'Income 2',
  'plan': 'advanced',
  'category': 'income',
  'riskLevel': 3,
  'investorProfile': 'moderate',
  'suggestedHorizon': '5-8 anni',
  'description': 'Portafoglio income orientato a Europa, obbligazioni corporate e azioni globali a '
                 'dividendo.',
  'warning': 'Può sottoperformare rispetto a un portafoglio globale growth in fasi dominate da USA e '
             'tecnologia.',
  'holdings': [{'name': 'iShares EUR Corporate Bond 1-5yr',
                'isin': 'IE00B4L60045',
                'weight': 35.0,
                'role': 'Obbligazioni corporate euro a breve-media scadenza'},
               {'name': 'iShares Core MSCI Europe',
                'isin': 'IE00B1YZSC51',
                'weight': 35.0,
                'role': 'Azionario europeo'},
               {'name': 'iShares STOXX Global Select Dividend 100',
                'isin': 'DE000A0F5UH1',
                'weight': 30.0,
                'role': 'Azionario globale orientato ai dividendi'}]},
 {'id': 'growth-small-cap-us',
  'name': 'Growth Small Cap & US',
  'originalName': 'Portfolio Growth',
  'plan': 'advanced',
  'category': 'growth',
  'riskLevel': 5,
  'investorProfile': 'high',
  'suggestedHorizon': '10+ anni',
  'description': 'Portafoglio growth aggressivo orientato a small cap globali e growth USA.',
  'warning': 'Prima di mostrarlo in produzione, normalizzare il nome completo e i dati dello strumento con '
             'ISIN IE00BJQRDN15. È un portafoglio ad alta volatilità.',
  'holdings': [{'name': 'iShares MSCI World Small Cap',
                'isin': 'IE00BF4RFH31',
                'weight': 40.0,
                'role': 'Azionario small cap globale'},
               {'name': 'JPMorgan US Growth Equity Active',
                'isin': 'IE0005CH3U28',
                'weight': 30.0,
                'role': 'Azionario growth USA a gestione attiva'},
               {'name': 'IE00BJQRDN15',
                'isin': 'IE00BJQRDN15',
                'weight': 20.0,
                'role': 'Componente growth aggiuntiva da normalizzare con dati ETF'},
               {'name': 'iShares Core MSCI World',
                'isin': 'IE00B4L5Y983',
                'weight': 10.0,
                'role': 'Base azionaria globale sviluppata'}]},
 {'id': 'satellite-value-globale',
  'name': 'Satellite Value Globale',
  'originalName': 'Value',
  'plan': 'advanced',
  'category': 'thematic',
  'riskLevel': 4,
  'investorProfile': 'high',
  'suggestedHorizon': '7-10+ anni',
  'description': 'Esposizione tematica/fattoriale al value globale.',
  'warning': 'È un satellite, non un portafoglio completo. Il fattore value può sottoperformare per periodi '
             'prolungati.',
  'holdings': [{'name': 'iShares Edge MSCI World Value Factor',
                'isin': 'IE00BP3QZB59',
                'weight': 100.0,
                'role': 'Esposizione fattoriale value globale'}]},
 {'id': 'tech-future-infrastructure',
  'name': 'Tech & Future Infrastructure',
  'originalName': 'Tech',
  'plan': 'advanced',
  'category': 'thematic',
  'riskLevel': 5,
  'investorProfile': 'high',
  'suggestedHorizon': '10+ anni',
  'description': 'Portafoglio tematico aggressivo su tecnologia, semiconduttori e infrastrutture energetiche '
                 'future.',
  'warning': 'Molto concentrato e volatile. Non deve essere trattato come portafoglio core.',
  'holdings': [{'name': 'iShares S&P 500 Information Technology Sector',
                'isin': 'IE00B3WJKG14',
                'weight': 50.0,
                'role': 'Tecnologia USA'},
               {'name': 'iShares MSCI Global Semiconductors',
                'isin': 'IE000I8KRLL9',
                'weight': 30.0,
                'role': 'Semiconduttori globali'},
               {'name': 'VanEck Uranium and Nuclear Technologies',
                'isin': 'IE000M7V94E1',
                'weight': 20.0,
                'role': 'Uranio e tecnologie nucleari'}]},
 {'id': 'satellite-ai-big-data',
  'name': 'Satellite AI & Big Data',
  'originalName': 'AI',
  'plan': 'advanced',
  'category': 'thematic',
  'riskLevel': 5,
  'investorProfile': 'high',
  'suggestedHorizon': '10+ anni',
  'description': 'Esposizione tematica ad aziende legate ad artificial intelligence e big data.',
  'warning': 'È un satellite tematico, non un portafoglio completo.',
  'holdings': [{'name': 'Xtrackers Artificial Intelligence & Big Data',
                'isin': 'IE00BGV5VN51',
                'weight': 100.0,
                'role': 'Esposizione tematica ad AI e Big Data'}]},
 {'id': 'industrials-blue-chips',
  'name': 'Industrials & Blue Chips',
  'originalName': 'Industrial',
  'plan': 'advanced',
  'category': 'thematic',
  'riskLevel': 4,
  'investorProfile': 'high',
  'suggestedHorizon': '7-10 anni',
  'description': 'Portafoglio tematico su blue chip USA e settore industriale europeo.',
  'warning': 'Il Dow Jones non rappresenta solo industriali puri, ma grandi aziende blue chip statunitensi.',
  'holdings': [{'name': 'iShares Dow Jones Industrial Average',
                'isin': 'IE00B53L4350',
                'weight': 50.0,
                'role': 'Blue chip USA'},
               {'name': 'iShares MSCI Europe Industrials Sector',
                'isin': 'IE00BMW42520',
                'weight': 50.0,
                'role': 'Settore industriale europeo'}]},
 {'id': 'satellite-space-economy',
  'name': 'Satellite Space Economy',
  'originalName': 'Space',
  'plan': 'advanced',
  'category': 'thematic',
  'riskLevel': 5,
  'investorProfile': 'high',
  'suggestedHorizon': '10+ anni',
  'description': 'Esposizione tematica alla space economy.',
  'warning': 'È un satellite molto concentrato e non deve sostituire un portafoglio globale diversificato.',
  'holdings': [{'name': 'VanEck Space Innovators',
                'isin': 'IE000YU9K6K2',
                'weight': 100.0,
                'role': 'Esposizione tematica alla space economy'}]},
 {'id': 'satellite-defense',
  'name': 'Satellite Defense',
  'originalName': 'Difesa',
  'plan': 'advanced',
  'category': 'thematic',
  'riskLevel': 5,
  'investorProfile': 'high',
  'suggestedHorizon': '10+ anni',
  'description': 'Esposizione tematica al settore della difesa.',
  'warning': 'Tema settoriale concentrato e potenzialmente non compatibile con preferenze ESG o etiche.',
  'holdings': [{'name': 'VanEck Defense',
                'isin': 'IE000YYE6WK5',
                'weight': 100.0,
                'role': 'Esposizione tematica al settore difesa'}]},
 {'id': 'megatrends-industriale-tech',
  'name': 'Megatrends Industriale & Tech',
  'originalName': 'Mixed',
  'plan': 'advanced',
  'category': 'thematic',
  'riskLevel': 5,
  'investorProfile': 'high',
  'suggestedHorizon': '10+ anni',
  'description': 'Portafoglio tematico multi-megatrend su tecnologia, AI, nucleare, difesa, space economy, '
                 'blue chip USA e industriali europei.',
  'warning': 'Portafoglio ad alta concentrazione settoriale. Non sostituisce un portafoglio core globale.',
  'holdings': [{'name': 'iShares S&P 500 Information Technology Sector',
                'isin': 'IE00B3WJKG14',
                'weight': 20.0,
                'role': 'Tecnologia USA'},
               {'name': 'VanEck Uranium and Nuclear Technologies',
                'isin': 'IE000M7V94E1',
                'weight': 10.0,
                'role': 'Uranio e nucleare'},
               {'name': 'Xtrackers Artificial Intelligence & Big Data',
                'isin': 'IE00BGV5VN51',
                'weight': 10.0,
                'role': 'AI e Big Data'},
               {'name': 'iShares Dow Jones Industrial Average',
                'isin': 'IE00B53L4350',
                'weight': 20.0,
                'role': 'Blue chip USA'},
               {'name': 'VanEck Space Innovators',
                'isin': 'IE000YU9K6K2',
                'weight': 10.0,
                'role': 'Space economy'},
               {'name': 'VanEck Defense', 'isin': 'IE000YYE6WK5', 'weight': 10.0, 'role': 'Difesa'},
               {'name': 'iShares MSCI Europe Industrials Sector',
                'isin': 'IE00BMW42520',
                'weight': 20.0,
                'role': 'Industriali europei'}]},
 {'id': 'governativo-breve-usd-eur',
  'name': 'Governativo Breve USD/EUR',
  'originalName': 'Obbligazioni Stati',
  'plan': 'advanced',
  'category': 'bond',
  'riskLevel': 2,
  'investorProfile': 'low',
  'suggestedHorizon': '2-5 anni',
  'description': 'Portafoglio governativo semplice diviso tra Treasury USA a breve scadenza e obbligazioni '
                 'governative dell’area euro.',
  'warning': 'La componente Treasury USA introduce rischio cambio EUR/USD.',
  'holdings': [{'name': 'iShares USD Treasury Bond 0-1yr',
                'isin': 'IE00BGSF1X88',
                'weight': 50.0,
                'role': 'Treasury USA a brevissima scadenza'},
               {'name': 'Vanguard EUR Eurozone Government Bond',
                'isin': 'IE00BH04GL39',
                'weight': 50.0,
                'role': 'Obbligazioni governative area euro'}]},
 {'id': 'esg-usa-industrials',
  'name': 'ESG USA & Industrials',
  'originalName': 'ESG 1',
  'plan': 'advanced',
  'category': 'esg',
  'riskLevel': 4,
  'investorProfile': 'moderate',
  'suggestedHorizon': '7-10 anni',
  'description': 'Portafoglio ESG orientato a Stati Uniti e settore industriale globale.',
  'warning': 'Non è un portafoglio ESG globale completo. È concentrato su USA e industriali.',
  'holdings': [{'name': 'iShares MSCI USA Screened',
                'isin': 'IE00BFNM3G45',
                'weight': 70.0,
                'role': 'Azionario USA con filtro screened'},
               {'name': 'Amundi S&P Global Industrials ESG',
                'isin': 'IE000LTA2082',
                'weight': 30.0,
                'role': 'Industriali globali con filtro ESG'}]},
 {'id': 'usa-climate-aligned',
  'name': 'USA Climate Aligned',
  'originalName': 'S&P 500 Paris Convention',
  'plan': 'advanced',
  'category': 'esg',
  'riskLevel': 4,
  'investorProfile': 'moderate',
  'suggestedHorizon': '7-10 anni',
  'description': 'Esposizione all’S&P 500 con filtro climatico Paris-Aligned.',
  'warning': 'È un’esposizione azionaria USA, non un portafoglio globale completo.',
  'holdings': [{'name': 'iShares S&P 500 Paris-Aligned Climate',
                'isin': 'IE00BMXC7V63',
                'weight': 100.0,
                'role': 'Esposizione USA large cap con filtro Paris-Aligned Climate'}]}]

STANDARD_PORTFOLIO_DISCLAIMER = (
    "I portfolio standard QuantInvest sono modelli educativi e benchmark di confronto. "
    "Non costituiscono consulenza finanziaria personalizzata né raccomandazione di acquisto o vendita."
)
